apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcpbackend
  template:
    metadata:
      labels:
        app: gcpbackend
    spec:
      containers:
      - name: gcpbackend
        image: gcr.io/gcp-my-picz/backendpiczamd:v2
        # image: gcr.io/gcp-my-picz/backendpiczarm:latest 
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  selector:
    app: gcpbackend
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer